"""initial db migration

Revision ID: 8add7dc085ba
Revises: 1cc78c8b43c1
Create Date: 2026-07-16 02:04:20.270072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8add7dc085ba'
down_revision: Union[str, Sequence[str], None] = '1cc78c8b43c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emails',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('processed_email', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'delivered', 'failed', name='emailstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name='emails_pk')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v7()'), nullable=False),
    sa.Column('type', sa.Enum('email', 'google', name='usertype'), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('google_id', sa.String(), nullable=True),
    sa.Column('google_email', sa.String(), nullable=True),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name='users_pk'),
    sa.UniqueConstraint('display_name'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('google_email')
    )
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_index('idx_users_google_id', 'users', ['google_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v7()'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='documents_created_by_fk', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='documents_pk')
    )
    op.create_index('idx_documents_created_by', 'documents', ['created_by'], unique=False)
    op.create_table('otp',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v7()'), nullable=False),
    sa.Column('otp', sa.String(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('valid', 'used', name='otpstatus'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='otp_user_id_fk', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='otp_id_pk'),
    sa.UniqueConstraint('otp')
    )
    op.create_index('idx_auth_otp', 'otp', ['otp'], unique=False)
    op.create_table('document_members',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('author', 'editor', 'viewer', name='documentroleenum'), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name='members_document_id_by_fk', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='members_user_id_by_fk', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('document_id', 'user_id', name='document_members_pk')
    )
    op.create_index('idx_document_members', 'document_members', ['document_id', 'user_id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_document_members', table_name='document_members')
    op.drop_table('document_members')
    op.drop_index('idx_auth_otp', table_name='otp')
    op.drop_table('otp')
    op.drop_index('idx_documents_created_by', table_name='documents')
    op.drop_table('documents')
    op.drop_index('idx_users_google_id', table_name='users')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_table('users')
    op.drop_table('emails')
    # ### end Alembic commands ###
